version: '3.8'
services:
  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mail-downloader
    restart: unless-stopped
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mail-downloader
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
volumes:
  mongo-data:
