version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./database/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=mail-downloader
    restart: unless-stopped
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mail-downloader
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo-data:
